WITH raw_cnes AS (
  -- 1. Retirar linhas com id_estabelecimento_cnes nulo
  SELECT *
  FROM `basedosdados-dev.br_ms_cnes_test_staging.estabelecimentos`
  WHERE CNES IS NOT NULL
),
cnes_add_muni AS (
  -- 2. Adicionar id_municipio e sigla_uf
  SELECT *
  FROM raw_cnes  
  LEFT JOIN (SELECT id_municipio, id_municipio_6, sigla_uf,
  FROM `basedosdados-dev.br_bd_diretorios_brasil.municipio`) as mun
  ON raw_cnes.CODUFMUN = mun.id_municipio_6
),
formatted_cnes AS (
  -- Apply data wrangling using the macro
  SELECT {{ data_wrangling(cnes_add_muni) }}
)
  -- 3. padronização, ordenação de colunas

  SELECT
  PARSE_DATE('%Y%m%d', DT_PUBLM) AS DATE,
  PARSE_DATE('%Y%m%d', DT_PUBLE) AS DATE,
  -- atencao ele usa um lstrip 00 
  PARSE_DATE('%Y%m%d', DT_EXPED) AS DATE,
  CAST(SUBSTR(DT_ATUAL, 1, 4) AS INT64) AS ano,
  CAST(SUBSTR(DT_ATUAL, 5, 2) AS INT64) AS mes,
  CAST(SUBSTR(COMPETEN, 1, 4) AS INT64) AS ano_competencia,
  CAST(SUBSTR(COMPETEN, 5, 2) AS INT64) AS mes_competencia,
  SAFE_CAST(sigla_uf AS STRING) sigla_uf, 
  SAFE_CAST(ano_atualizacao AS INT64) ano_atualizacao,
  SAFE_CAST(mes_atualizacao AS INT64) mes_atualizacao,
  SAFE_CAST(id_municipio AS STRING) id_municipio,
  SAFE_CAST(id_municipio_6 AS STRING) id_municipio_6,
  SAFE_CAST(id_regiao_saude AS STRING) id_regiao_saude,
  SAFE_CAST(id_microrregiao_saude AS STRING) id_microrregiao_saude,
  SAFE_CAST(id_distrito_sanitario AS STRING) id_distrito_sanitario,
  SAFE_CAST(id_distrito_administrativo AS STRING) id_distrito_administrativo,
  SAFE_CAST(cep AS STRING) cep,
  SAFE_CAST(id_estabelecimento_cnes AS STRING) id_estabelecimento_cnes,
  SAFE_CAST(tipo_pessoa AS STRING) tipo_pessoa,
  SAFE_CAST(cpf_cnpj  AS STRING) cpf_cnpj,
  SAFE_CAST(tipo_grau_dependencia AS STRING) tipo_grau_dependencia,
  SAFE_CAST(cnpj_mantenedora AS STRING) cnpj_mantenedora,
  SAFE_CAST(tipo_retencao_tributos_mantenedora AS STRING) tipo_retencao_tributos_mantenedora,
  SAFE_CAST(indicador_vinculo_sus AS INT64) indicador_vinculo_sus,
  SAFE_CAST(tipo_gestao AS STRING) tipo_gestao,
  SAFE_CAST(tipo_esfera_administrativa AS STRING) tipo_esfera_administrativa,
  SAFE_CAST(tipo_retencao_tributos AS STRING) tipo_retencao_tributos,
  SAFE_CAST(tipo_atividade_ensino_pesquisa AS STRING) tipo_atividade_ensino_pesquisa,
  SAFE_CAST(tipo_natureza_administrativa AS STRING) tipo_natureza_administrativa,
  SAFE_CAST(id_natureza_juridica AS STRING) id_natureza_juridica,
  SAFE_CAST(tipo_fluxo_atendimento AS STRING) tipo_fluxo_atendimento,
  SAFE_CAST(tipo_unidade AS STRING) tipo_unidade,
  SAFE_CAST(tipo_turno AS STRING) tipo_turno,
  SAFE_CAST(tipo_nivel_hierarquia AS STRING) tipo_nivel_hierarquia,
  SAFE_CAST(tipo_prestador AS STRING) tipo_prestador,
  SAFE_CAST(banco AS STRING) banco,
  SAFE_CAST(agencia AS STRING) agencia,
  SAFE_CAST(conta_corrente AS STRING) conta_corrente,
  SAFE_CAST(id_contrato_municipio_sus AS STRING) id_contrato_municipio_sus,
  SAFE_CAST(data_publicacao_contrato_municipal AS DATE) data_publicacao_contrato_municipal,
  SAFE_CAST(id_contrato_estado_sus AS STRING) id_contrato_estado_sus,
  SAFE_CAST(data_publicacao_contrato_estadual AS DATE) data_publicacao_contrato_estadual,
  SAFE_CAST(numero_alvara AS STRING) numero_alvara,
  SAFE_CAST(data_expedicao_alvara AS DATE) data_expedicao_alvara,
  SAFE_CAST(tipo_orgao_expedidor AS STRING) tipo_orgao_expedidor,
  SAFE_CAST(tipo_avaliacao_acreditacao_hospitalar AS STRING) tipo_avaliacao_acreditacao_hospitalar,
  SAFE_CAST(tipo_classificacao_acreditacao_hospitalar AS STRING) tipo_classificacao_acreditacao_hospitalar,
  CAST(SUBSTR(DT_ACRED, 1, 4) AS INT64) AS ano_acreditacao,
  CAST(SUBSTR(DT_ACRED, 5, 2) AS INT64) AS mes_acreditacao,
  SAFE_CAST(tipo_avaliacao_pnass AS INT64) tipo_avaliacao_pnass,
  CAST(SUBSTR(DT_PNASS, 1, 4) as INT64) AS ano_avaliacao_pnass,
  CAST(SUBSTR(DT_PNASS, 5, 2) AS INT64) AS mes_avaliacao_pnass,
  SAFE_CAST(indicador_atencao_ambulatorial AS INT64) indicador_atencao_ambulatorial,
  SAFE_CAST(indicador_gestao_basica_ambulatorial_estadual AS INT64) indicador_gestao_basica_ambulatorial_estadual,
  SAFE_CAST(indicador_gestao_basica_ambulatorial_municipal AS INT64) indicador_gestao_basica_ambulatorial_municipal,
  SAFE_CAST(indicador_gestao_media_ambulatorial_estadual AS INT64) indicador_gestao_media_ambulatorial_estadual,
  SAFE_CAST(indicador_gestao_media_ambulatorial_municipal AS INT64) indicador_gestao_media_ambulatorial_municipal,
  SAFE_CAST(indicador_gestao_alta_ambulatorial_estadual AS INT64) indicador_gestao_alta_ambulatorial_estadual,
  SAFE_CAST(indicador_gestao_alta_ambulatorial_municipal AS INT64) indicador_gestao_alta_ambulatorial_municipal,
  SAFE_CAST(indicador_atencao_hospitalar AS INT64) indicador_atencao_hospitalar,
  SAFE_CAST(indicador_gestao_media_hospitalar_estadual AS INT64) indicador_gestao_media_hospitalar_estadual,
  SAFE_CAST(indicador_gestao_media_hospitalar_municipal AS INT64) indicador_gestao_media_hospitalar_municipal,
  SAFE_CAST(indicador_gestao_alta_hospitalar_estadual AS INT64) indicador_gestao_alta_hospitalar_estadual,
  SAFE_CAST(indicador_gestao_alta_hospitalar_municipal AS INT64) indicador_gestao_alta_hospitalar_municipal,
  SAFE_CAST(indicador_gestao_hospitalar_estadual AS INT64) indicador_gestao_hospitalar_estadual,
  SAFE_CAST(indicador_gestao_hospitalar_municipal AS INT64) indicador_gestao_hospitalar_municipal,
  SAFE_CAST(indicador_leito_hospitalar AS INT64) indicador_leito_hospitalar,
  SAFE_CAST(quantidade_leito_cirurgico AS INT64) quantidade_leito_cirurgico,
  SAFE_CAST(quantidade_leito_clinico AS INT64) quantidade_leito_clinico,
  SAFE_CAST(quantidade_leito_complementar AS INT64) quantidade_leito_complementar,
  SAFE_CAST(quantidade_leito_repouso_pediatrico_urgencia AS INT64) quantidade_leito_repouso_pediatrico_urgencia,
  SAFE_CAST(quantidade_leito_repouso_feminino_urgencia AS INT64) quantidade_leito_repouso_feminino_urgencia,
  SAFE_CAST(quantidade_leito_repouso_masculino_urgencia AS INT64) quantidade_leito_repouso_masculino_urgencia,
  SAFE_CAST(quantidade_leito_repouso_indiferenciado_urgencia AS INT64) quantidade_leito_repouso_indiferenciado_urgencia,
  SAFE_CAST(indicador_instalacao_urgencia AS INT64) indicador_instalacao_urgencia,
  SAFE_CAST(quantidade_consultorio_pediatrico_urgencia AS INT64) quantidade_consultorio_pediatrico_urgencia,
  SAFE_CAST(quantidade_consultorio_feminino_urgencia AS INT64) quantidade_consultorio_feminino_urgencia,
  SAFE_CAST(quantidade_consultorio_masculino_urgencia AS INT64) quantidade_consultorio_masculino_urgencia,
  SAFE_CAST(quantidade_consultorio_indiferenciado_urgencia AS INT64) quantidade_consultorio_indiferenciado_urgencia,
  SAFE_CAST(quantidade_consultorio_odontologia_urgencia AS INT64) quantidade_consultorio_odontologia_urgencia,
  SAFE_CAST(quantidade_sala_repouso_pediatrico_urgencia AS INT64) quantidade_sala_repouso_pediatrico_urgencia,
  SAFE_CAST(quantidade_sala_repouso_feminino_urgencia AS INT64) quantidade_sala_repouso_feminino_urgencia,
  SAFE_CAST(quantidade_sala_repouso_masculino_urgencia AS INT64) quantidade_sala_repouso_masculino_urgencia,
  SAFE_CAST(quantidade_sala_repouso_indiferenciado_urgencia AS INT64) quantidade_sala_repouso_indiferenciado_urgencia,
  SAFE_CAST(quantidade_equipos_odontologia_urgencia AS INT64) quantidade_equipos_odontologia_urgencia,
  SAFE_CAST(quantidade_sala_higienizacao_urgencia AS INT64) quantidade_sala_higienizacao_urgencia,
  SAFE_CAST(quantidade_sala_gesso_urgencia AS INT64) quantidade_sala_gesso_urgencia,
  SAFE_CAST(quantidade_sala_curativo_urgencia AS INT64) quantidade_sala_curativo_urgencia,
  SAFE_CAST(quantidade_sala_pequena_cirurgia_urgencia AS INT64) quantidade_sala_pequena_cirurgia_urgencia,
  SAFE_CAST(quantidade_consultorio_medico_urgencia AS INT64) quantidade_consultorio_medico_urgencia,
  SAFE_CAST(indicador_instalacao_ambulatorial AS INT64) indicador_instalacao_ambulatorial,
  SAFE_CAST(quantidade_consultorio_clinica_basica_ambulatorial AS INT64) quantidade_consultorio_clinica_basica_ambulatorial,
  SAFE_CAST(quantidade_consultorio_clinica_especializada_ambulatorial AS INT64) quantidade_consultorio_clinica_especializada_ambulatorial,
  SAFE_CAST(quantidade_consultorio_clinica_indiferenciada_ambulatorial AS INT64) quantidade_consultorio_clinica_indiferenciada_ambulatorial,
  SAFE_CAST(quantidade_consultorio_nao_medico_ambulatorial AS INT64) quantidade_consultorio_nao_medico_ambulatorial,
  SAFE_CAST(quantidade_sala_repouso_feminino_ambulatorial AS INT64) quantidade_sala_repouso_feminino_ambulatorial,
  SAFE_CAST(quantidade_leito_repouso_feminino_ambulatorial AS INT64) quantidade_leito_repouso_feminino_ambulatorial,
  SAFE_CAST(quantidade_sala_repouso_masculino_ambulatorial AS INT64) quantidade_sala_repouso_masculino_ambulatorial,
  SAFE_CAST(quantidade_leito_repouso_masculino_ambulatorial AS INT64) quantidade_leito_repouso_masculino_ambulatorial,
  SAFE_CAST(quantidade_sala_repouso_pediatrico_ambulatorial AS INT64) quantidade_sala_repouso_pediatrico_ambulatorial,
  SAFE_CAST(quantidade_leito_repouso_pediatrico_ambulatorial AS INT64) quantidade_leito_repouso_pediatrico_ambulatorial,
  SAFE_CAST(quantidade_sala_repouso_indiferenciado_ambulatorial AS INT64) quantidade_sala_repouso_indiferenciado_ambulatorial,
  SAFE_CAST(quantidade_leito_repouso_indiferenciado_ambulatorial AS INT64) quantidade_leito_repouso_indiferenciado_ambulatorial,
  SAFE_CAST(quantidade_consultorio_odontologia_ambulatorial AS INT64) quantidade_consultorio_odontologia_ambulatorial,
  SAFE_CAST(quantidade_equipos_odontologia_ambulatorial AS INT64) quantidade_equipos_odontologia_ambulatorial,
  SAFE_CAST(quantidade_sala_pequena_cirurgia_ambulatorial AS INT64) quantidade_sala_pequena_cirurgia_ambulatorial,
  SAFE_CAST(quantidade_sala_enfermagem_ambulatorial AS INT64) quantidade_sala_enfermagem_ambulatorial,
  SAFE_CAST(quantidade_sala_imunizacao_ambulatorial AS INT64) quantidade_sala_imunizacao_ambulatorial,
  SAFE_CAST(quantidade_sala_nebulizacao_ambulatorial AS INT64) quantidade_sala_nebulizacao_ambulatorial,
  SAFE_CAST(quantidade_sala_gesso_ambulatorial AS INT64) quantidade_sala_gesso_ambulatorial,
  SAFE_CAST(quantidade_sala_curativo_ambulatorial AS INT64) quantidade_sala_curativo_ambulatorial,
  SAFE_CAST(quantidade_sala_cirurgia_ambulatorial AS INT64) quantidade_sala_cirurgia_ambulatorial,
  SAFE_CAST(indicador_instalacao_hospitalar AS INT64) indicador_instalacao_hospitalar,
  SAFE_CAST(indicador_instalacao_hospitalar_centro_cirurgico AS INT64) indicador_instalacao_hospitalar_centro_cirurgico,
  SAFE_CAST(quantidade_sala_cirurgia_centro_cirurgico AS INT64) quantidade_sala_cirurgia_centro_cirurgico,
  SAFE_CAST(quantidade_sala_recuperacao_centro_cirurgico AS INT64) quantidade_sala_recuperacao_centro_cirurgico,
  SAFE_CAST(quantidade_leito_recuperacao_centro_cirurgico AS INT64) quantidade_leito_recuperacao_centro_cirurgico,
  SAFE_CAST(quantidade_sala_cirurgia_ambulatorial_centro_cirurgico AS INT64) quantidade_sala_cirurgia_ambulatorial_centro_cirurgico,
  SAFE_CAST(indicador_instalacao_hospitalar_centro_obstetrico AS INT64) indicador_instalacao_hospitalar_centro_obstetrico,
  SAFE_CAST(quantidade_sala_pre_parto_centro_obstetrico AS INT64) quantidade_sala_pre_parto_centro_obstetrico,
  SAFE_CAST(quantidade_leito_pre_parto_centro_obstetrico AS INT64) quantidade_leito_pre_parto_centro_obstetrico,
  SAFE_CAST(quantidade_sala_parto_normal_centro_obstetrico AS INT64) quantidade_sala_parto_normal_centro_obstetrico,
  SAFE_CAST(quantidade_sala_curetagem_centro_obstetrico AS INT64) quantidade_sala_curetagem_centro_obstetrico,
  SAFE_CAST(quantidade_sala_cirurgia_centro_obstetrico AS INT64) quantidade_sala_cirurgia_centro_obstetrico,
  SAFE_CAST(indicador_instalacao_hospitalar_neonatal AS INT64) indicador_instalacao_hospitalar_neonatal,
  SAFE_CAST(quantidade_leito_recem_nascido_normal_neonatal AS INT64) quantidade_leito_recem_nascido_normal_neonatal,
  SAFE_CAST(quantidade_leito_recem_nascido_patologico_neonatal AS INT64) quantidade_leito_recem_nascido_patologico_neonatal,
  SAFE_CAST(quantidade_leito_conjunto_neonatal AS INT64) quantidade_leito_conjunto_neonatal,
  SAFE_CAST(indicador_servico_apoio AS INT64) indicador_servico_apoio,
  SAFE_CAST(indicador_servico_same_spp_proprio AS INT64) indicador_servico_same_spp_proprio,
  SAFE_CAST(indicador_servico_same_spp_terceirizado AS INT64) indicador_servico_same_spp_terceirizado,
  SAFE_CAST(indicador_servico_social_proprio AS INT64) indicador_servico_social_proprio,
  SAFE_CAST(indicador_servico_social_terceirizado AS INT64) indicador_servico_social_terceirizado,
  SAFE_CAST(indicador_servico_farmacia_proprio AS INT64) indicador_servico_farmacia_proprio,
  SAFE_CAST(indicador_servico_farmacia_terceirizado AS INT64) indicador_servico_farmacia_terceirizado,
  SAFE_CAST(indicador_servico_esterilizacao_proprio AS INT64) indicador_servico_esterilizacao_proprio,
  SAFE_CAST(indicador_servico_esterilizacao_terceirizado AS INT64) indicador_servico_esterilizacao_terceirizado,
  SAFE_CAST(indicador_servico_nutricao_proprio AS INT64) indicador_servico_nutricao_proprio,
  SAFE_CAST(indicador_servico_nutricao_terceirizado AS INT64) indicador_servico_nutricao_terceirizado,
  SAFE_CAST(indicador_servico_lactario_proprio AS INT64) indicador_servico_lactario_proprio,
  SAFE_CAST(indicador_servico_lactario_terceirizado AS INT64) indicador_servico_lactario_terceirizado,
  SAFE_CAST(indicador_servico_banco_leite_proprio AS INT64) indicador_servico_banco_leite_proprio,
  SAFE_CAST(indicador_servico_banco_leite_terceirizado AS INT64) indicador_servico_banco_leite_terceirizado,
  SAFE_CAST(indicador_servico_lavanderia_proprio AS INT64) indicador_servico_lavanderia_proprio,
  SAFE_CAST(indicador_servico_lavanderia_terceirizado AS INT64) indicador_servico_lavanderia_terceirizado,
  SAFE_CAST(indicador_servico_manutencao_proprio AS INT64) indicador_servico_manutencao_proprio,
  SAFE_CAST(indicador_servico_manutencao_terceirizado AS INT64) indicador_servico_manutencao_terceirizado,
  SAFE_CAST(indicador_servico_ambulancia_proprio AS INT64) indicador_servico_ambulancia_proprio,
  SAFE_CAST(indicador_servico_ambulancia_terceirizado AS INT64) indicador_servico_ambulancia_terceirizado,
  SAFE_CAST(indicador_servico_necroterio_proprio AS INT64) indicador_servico_necroterio_proprio,
  SAFE_CAST(indicador_servico_necroterio_terceirizado AS INT64) indicador_servico_necroterio_terceirizado,
  SAFE_CAST(indicador_coleta_residuo AS INT64) indicador_coleta_residuo,
  SAFE_CAST(indicador_coleta_residuo_biologico AS INT64) indicador_coleta_residuo_biologico,
  SAFE_CAST(indicador_coleta_residuo_quimico AS INT64) indicador_coleta_residuo_quimico,
  SAFE_CAST(indicador_coleta_rejeito_radioativo AS INT64) indicador_coleta_rejeito_radioativo,
  SAFE_CAST(indicador_coleta_rejeito_comum AS INT64) indicador_coleta_rejeito_comum,
  SAFE_CAST(indicador_comissao AS INT64) indicador_comissao,
  SAFE_CAST(indicador_comissao_etica_medica AS INT64) indicador_comissao_etica_medica,
  SAFE_CAST(indicador_comissao_etica_enfermagem AS INT64) indicador_comissao_etica_enfermagem,
  SAFE_CAST(indicador_comissao_farmacia_terapeutica AS INT64) indicador_comissao_farmacia_terapeutica,
  SAFE_CAST(indicador_comissao_controle_infeccao AS INT64) indicador_comissao_controle_infeccao,
  SAFE_CAST(indicador_comissao_apropriacao_custos AS INT64) indicador_comissao_apropriacao_custos,
  SAFE_CAST(indicador_comissao_cipa AS INT64) indicador_comissao_cipa,
  SAFE_CAST(indicador_comissao_revisao_prontuario AS INT64) indicador_comissao_revisao_prontuario,
  SAFE_CAST(indicador_comissao_revisao_documentacao AS INT64) indicador_comissao_revisao_documentacao,
  SAFE_CAST(indicador_comissao_analise_obito_biopisias AS INT64) indicador_comissao_analise_obito_biopisias,
  SAFE_CAST(indicador_comissao_investigacao_epidemiologica AS INT64) indicador_comissao_investigacao_epidemiologica,
  SAFE_CAST(indicador_comissao_notificacao_doencas AS INT64) indicador_comissao_notificacao_doencas,
  SAFE_CAST(indicador_comissao_zoonose_vetores AS INT64) indicador_comissao_zoonose_vetores,
  SAFE_CAST(indicador_atendimento_prestado AS INT64) indicador_atendimento_prestado,
  SAFE_CAST(indicador_atendimento_internacao_sus AS INT64) indicador_atendimento_internacao_sus,
  SAFE_CAST(indicador_atendimento_internacao_particular AS INT64) indicador_atendimento_internacao_particular,
  SAFE_CAST(indicador_atendimento_internacao_plano_seguro_proprio AS INT64) indicador_atendimento_internacao_plano_seguro_proprio,
  SAFE_CAST(indicador_atendimento_internacao_plano_seguro_terceiro AS INT64) indicador_atendimento_internacao_plano_seguro_terceiro,
  SAFE_CAST(indicador_atendimento_internacao_plano_saude_publico AS INT64) indicador_atendimento_internacao_plano_saude_publico,
  SAFE_CAST(indicador_atendimento_internacao_plano_saude_privado AS INT64) indicador_atendimento_internacao_plano_saude_privado,
  SAFE_CAST(indicador_atendimento_ambulatorial_sus AS INT64) indicador_atendimento_ambulatorial_sus,
  SAFE_CAST(indicador_atendimento_ambulatorial_particular AS INT64) indicador_atendimento_ambulatorial_particular,
  SAFE_CAST(indicador_atendimento_ambulatorial_plano_seguro_proprio AS INT64) indicador_atendimento_ambulatorial_plano_seguro_proprio,
  SAFE_CAST(indicador_atendimento_ambulatorial_plano_seguro_terceiro AS INT64) indicador_atendimento_ambulatorial_plano_seguro_terceiro,
  SAFE_CAST(indicador_atendimento_ambulatorial_plano_saude_publico AS INT64) indicador_atendimento_ambulatorial_plano_saude_publico,
  SAFE_CAST(indicador_atendimento_ambulatorial_plano_saude_privado AS INT64) indicador_atendimento_ambulatorial_plano_saude_privado,
  SAFE_CAST(indicador_atendimento_sadt_sus AS INT64) indicador_atendimento_sadt_sus,
  SAFE_CAST(indicador_atendimento_sadt_privado AS INT64) indicador_atendimento_sadt_privado,
  SAFE_CAST(indicador_atendimento_sadt_plano_seguro_proprio AS INT64) indicador_atendimento_sadt_plano_seguro_proprio,
  SAFE_CAST(indicador_atendimento_sadt_plano_seguro_terceiro AS INT64) indicador_atendimento_sadt_plano_seguro_terceiro,
  SAFE_CAST(indicador_atendimento_sadt_plano_saude_publico AS INT64) indicador_atendimento_sadt_plano_saude_publico,
  SAFE_CAST(indicador_atendimento_sadt_plano_saude_privado AS INT64) indicador_atendimento_sadt_plano_saude_privado,
  SAFE_CAST(indicador_atendimento_urgencia_sus AS STRING) indicador_atendimento_urgencia_sus,
  SAFE_CAST(indicador_atendimento_urgencia_privado AS INT64) indicador_atendimento_urgencia_privado,
  SAFE_CAST(indicador_atendimento_urgencia_plano_seguro_proprio AS INT64) indicador_atendimento_urgencia_plano_seguro_proprio,
  SAFE_CAST(indicador_atendimento_urgencia_plano_seguro_terceiro AS INT64) indicador_atendimento_urgencia_plano_seguro_terceiro,
  SAFE_CAST(indicador_atendimento_urgencia_plano_saude_publico AS INT64) indicador_atendimento_urgencia_plano_saude_publico,
  SAFE_CAST(indicador_atendimento_urgencia_plano_saude_privado AS INT64) indicador_atendimento_urgencia_plano_saude_privado,
  SAFE_CAST(indicador_atendimento_outros_sus AS INT64) indicador_atendimento_outros_sus,
  SAFE_CAST(indicador_atendimento_outros_privado AS INT64) indicador_atendimento_outros_privado,
  SAFE_CAST(indicador_atendimento_outros_plano_seguro_proprio AS INT64) indicador_atendimento_outros_plano_seguro_proprio,
  SAFE_CAST(indicador_atendimento_outros_plano_seguro_terceiro AS INT64) indicador_atendimento_outros_plano_seguro_terceiro,
  SAFE_CAST(indicador_atendimento_outros_plano_saude_publico AS INT64) indicador_atendimento_outros_plano_saude_publico,
  SAFE_CAST(indicador_atendimento_outros_plano_saude_privado AS INT64) indicador_atendimento_outros_plano_saude_privado,
  SAFE_CAST(indicador_atendimento_vigilancia_sus AS INT64) indicador_atendimento_vigilancia_sus,
  SAFE_CAST(indicador_atendimento_vigilancia_privado AS INT64) indicador_atendimento_vigilancia_privado,
  SAFE_CAST(indicador_atendimento_vigilancia_plano_seguro_proprio AS INT64) indicador_atendimento_vigilancia_plano_seguro_proprio,
  SAFE_CAST(indicador_atendimento_vigilancia_plano_seguro_terceiro AS INT64) indicador_atendimento_vigilancia_plano_seguro_terceiro,
  SAFE_CAST(indicador_atendimento_vigilancia_plano_saude_publico AS INT64) indicador_atendimento_vigilancia_plano_saude_publico,
  SAFE_CAST(indicador_atendimento_vigilancia_plano_saude_privado AS INT64) indicador_atendimento_vigilancia_plano_saude_privado,
  SAFE_CAST(indicador_atendimento_regulacao_sus AS INT64) indicador_atendimento_regulacao_sus,
  SAFE_CAST(indicador_atendimento_regulacao_privado AS INT64) indicador_atendimento_regulacao_privado,
  SAFE_CAST(indicador_atendimento_regulacao_plano_seguro_proprio AS INT64) indicador_atendimento_regulacao_plano_seguro_proprio,
  SAFE_CAST(indicador_atendimento_regulacao_plano_seguro_terceiro AS INT64) indicador_atendimento_regulacao_plano_seguro_terceiro,
  SAFE_CAST(indicador_atendimento_regulacao_plano_saude_publico AS INT64) indicador_atendimento_regulacao_plano_saude_publico,
  SAFE_CAST(indicador_atendimento_regulacao_plano_saude_privado AS INT64) indicador_atendimento_regulacao_plano_saude_privado
  FROM formatted_cnes AS t
