{{ config(alias='domicilios_pelo_menos_um_moradores_terras_indigenas',schema='br_ibge_censo_2022') }}
SELECT
SAFE_CAST(terra_indigena AS STRING) terra_indigena,
SAFE_CAST(domicilios_terras_indigenas_pelo_menos_um AS INT64) domicilios_terras_indigenas_pelo_menos_um,
SAFE_CAST(moradores_domicilios_terras_indigenas_pelo_menos_um AS INT64) moradores_domicilios_terras_indigenas_pelo_menos_um,
SAFE_CAST(moradores_indigenas_domicilios_terras_indigenas_pelo_menos_um AS INT64) moradores_indigenas_domicilios_terras_indigenas_pelo_menos_um,
SAFE_CAST(media_moradores_domicilios_terras_indigenas_pelo_menos_um AS FLOAT64) media_moradores_domicilios_terras_indigenas_pelo_menos_um,
SAFE_CAST(media_moradores_indigenas_domicilios_terras_indigenas_pelo_menos_um AS FLOAT64) media_moradores_indigenas_domicilios_terras_indigenas_pelo_menos_um,
FROM basedosdados-dev.br_ibge_censo_2022_staging.domicilios_pelo_menos_um_moradores_terras_indigenas AS t

